### PR TITLE
Adding information about data source to merged data

### PR DESCRIPTION
**Pull request by 808sAndBR**
I was unable to get GDAL working on my computer but I was able to run the relevant parts of the script with my changes and they work for me. It would be great if someone that has the geo_classifier working could run this once and add the updated data files before merging.

The biggest change (besides adding the new columns) is the all_housing_data variable. The way it used to be wasn't getting updated with the new columns so I changed it to being created with an empty DataFrame and getting appended to lower in the function.

### CODE REVIEW

**Comment by qwwqwwq** [comment]
Ah sorry about troubles with GDAL, I need to add a requirements.txt file / env setup instructions.

on OSX you can do `brew install gdal --HEAD`, the `pip install osgeo`

**Comment by qwwqwwq** [comment]
LGTM!

**Comment by 808sAndBR** [comment]
Hmmm it was looking good at first but i'm hitting some really ugly issues with brew on this. 

Since I don't *really* need to be able to run this locally and we just need it ran once to generate the cleaned data do you mind checking out this branch, running cleaner.py, and committing the new json & csv files on this branch? Then we can merge it. 

Or if that's too annoying, I can go further down this GDAL rabbit hole.

**Comment by qwwqwwq** [comment]
Ran you changes and updated the CSV, landing.. :)

**Pull request merged**
